### ISSUE TITLE
NullPointerException in 953

### ISSUE THREAD

**Issue by sarumjanuch** [jitsi/jitsi-videobridge#485]
On latest stable release (953), we noticed random occurrence of situation, where jvb constantly writing in huge amount following lines in to the log file, until channel expires:

```
Jun  5 12:40:48 home.local JVB SEVERE: [737] org.jitsi.util.concurrent.RecurringRunnableExecutor.log() The invocation of the method org.jitsi.videobridge.cc.BandwidthProbing.run() threw an exception.
java.lang.NullPointerException
```

**Comment by gpolitis** [comment]
Thanks for reporting Eugene, I will have a look.

**Comment by gpolitis** [comment]
Hi Eugene, could you please try to update the bridge and try again. I believe this is fixed in 961.

**Comment by sarumjanuch** [comment]
Thanks a lot for letting me know. We will try, i will report you, as soon as i will have something.

**Comment by ajorkowski** [comment]
Just to jump in here - I recently updated to latest (967) from a pre-953 version and I am seeing the same error message. It doesn't seem to happen with a fresh channel, however I can replicate the issue pretty quickly if I disconnect a local track (via lib-jitsi-meet) and re-attach the same local track to a conference.

After I do that I no longer see the contents of the stream in the other clients - that is, I do get a RemoteJitsiTrack but the attached video element is blank - and I see these errors in the logs. 

Also this issue seems to persist in the videobridge as even if I refresh all browser windows I am not able to get a working video stream if I log back into the same room.

**Comment by sarumjanuch** [comment]
I have just checked log files, we have 961, and i still see a lot of:
```
Jun  5 11:28:54 home.local JVB SEVERE: [101] org.jitsi.util.concurrent.RecurringRunnableExecutor.log() The invocation of the method org.jitsi.videobridge.cc.BandwidthProbing.run() threw an exception.
java.lang.NullPointerException
.at org.jitsi.videobridge.cc.BandwidthProbing.run(BandwidthProbing.java:138)
.at org.jitsi.util.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:212)
.at org.jitsi.util.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:288)
.at org.jitsi.util.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
.at org.jitsi.util.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:324)
```

**Comment by sarumjanuch** [comment]
Did test in 997, the issue still persist, could i help somehow, to help to resolve this?

**Comment by rdelay** [comment]
We just upgraded our video bridge to 995-1, it does seem hit and miss when changing video streams.  It can take anywhere from 1 to 2 minutes for the remote side to see the new stream.  Please let me know if I can provide anymore information.

JVB 2017-11-01 14:07:54.710 SEVERE: [270646] org.jitsi.util.concurrent.RecurringRunnableExecutor.log() The invocation of the method org.jitsi.videobridge.cc.BandwidthProbing.run() threw an exception.
java.lang.NullPointerException
	at org.jitsi.videobridge.cc.BandwidthProbing.run(BandwidthProbing.java:138)
	at org.jitsi.util.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:212)
	at org.jitsi.util.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:288)
	at org.jitsi.util.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
	at org.jitsi.util.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:324)

**Comment by jitsi-developers** [comment]
Hi guys,

Do you have a plan to address the problem? We’re experiencing the same issue with exactly the same error.

Thanks,
Alex

**Comment by sarumjanuch** [comment]
Don't know is it related, just tested in 1009, seems like the old problem is gone, but just traped into another one, I would say, with same steps to reproduce, but with a bit other consequences. https://pastebin.com/hLhFnpfX Should I open a new issue?

**Comment by gpolitis** [comment]
Thanks very much for reporting @sarumjanuch. We will take a look today and provide a fix for that later today.

**Comment by sarumjanuch** [comment]
I am happy to help here, if you will need any additional information, feel free to ping me here, or via e-mail, i will be glad to re-test as soon as Jenkins will build new linux assemblies

**Comment by sarumjanuch** [comment]
Just have rebuilt rpms, and tested 1010, seems like i am unable to reproduce this issue, thanks a lot! Have a good one.

**Comment by gpolitis** [comment]
Thank _you_ for reporting the issues.
