### ISSUE TITLE
jvb service not passing --host flag | "Something went wrong" loop

### ISSUE THREAD

**Issue by Ark74** [jitsi/jitsi-videobridge#731]
## Description
---
On the latest update from debian unstable repository, I'm having some issues with the jvb looping the conference as described here: https://community.jitsi.org/t/stuck-in-something-went-wrong-loop-once-second-member-connected/16091/12?u=ark74
## Current behavior
---
Whenever a user set a conference and is joined by a second one, this breaks and loops back.
Seems that this is only present on the unstable branch, since on the stable one other users can still join.
## Expected Behavior
---
Being able to join a conference without issues.
## Possible Solution
---
Seems like with the use of the systemd service for jvb, on older installations don't pass the --host flag even when it's set on /etc/jitsi/videobridge/config

Manually edit: /lib/systemd/system/jitsi-videobridge.service
And set localhost manually :laughing: 
**It works!**

## Steps to reproduce
---
1. Install a fresh unstable branch 
2. Try to join the conference two persons or more, it will crash.
3. Edit /etc/jitsi/videobridge/config to set JVB_HOST as localhost and restart the system.
4. `systemctl status jitsi-videobridge.service `

Will show that the JVB_HOST as localhost flag is not being passed.

`"...zrtp4j-light-3.2.0-jitsi-1-20150723.002345-1.jar org.jitsi.videobridge.Main --host= --domain=jitsi.si..."
`
# Environment details
---
*buntu 16.04 // Others find this issue at the community forum.

**Comment by damencho** [comment]
Does it work if you add something else, other than localhost ... 
A few months ago I've added the systemd unit file https://github.com/jitsi/jitsi-videobridge/blob/master/resources/install/debian/jitsi-videobridge.service#L19
And it should be working just fine.

**Comment by Ark74** [comment]
No, as for the date tested, nothing passed, 127.0.0.1, localhost, they passed on stable.

I see today there are new updates, I'll update and report back.

**Comment by Ark74** [comment]
Just tested today with a new instance.
The JVB_HOST in /etc/jitsi/videobridge/config is not passing to actual executed service.

The service file reads on the ExecStart,

`ExecStart=/bin/bash -c "exec /usr/share/jitsi-videobridge/jvb.sh --host=${JVB_HOST:-localhost} --domain=${JVB_HOSTNAME} --port=${JVB_PORT} --secret=${JVB_SECRET} ${JVB_OPTS} ...`

And systemctl reports,

```
● jitsi-videobridge.service - Jitsi Videobridge
   Loaded: loaded (/lib/systemd/system/jitsi-videobridge.service; enabled; vendor preset: enabled)
   Active: active (running) since lun 2018-12-17 11:41:55 CST; 3min 17s ago
  Process: 15456 ExecStartPost=/bin/bash -c echo $MAINPID > /var/run/jitsi-videobridge/jitsi-videobridge.pid (code=exited, status=0/SUCCESS)
 Main PID: 15455 (java)
    Tasks: 29 (limit: 65000)
   CGroup: /system.slice/jitsi-videobridge.service
           └─15455 java -Xmx3072m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Djava.library.path=/usr/share/jitsi-videobridge/lib/native/linux-64 -Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=videobridge -Dnet.java.sip.communicator.SC_LOG_DIR_LOCATION=/var/log/jitsi -Djava.util.logging.config.file=/etc/jitsi/videobridge/logging.properties -cp /usr/share/jitsi-videobridge/jitsi-videobridge.jar:/usr/share/jitsi-videobridge/lib/agafua-syslog-0.4.jar:/usr/share/jitsi-videobridge/lib/annotations-15.0.jar:/usr/share/jitsi-videobridge/lib/bccontrib-1.0.jar:/usr/share/jitsi-videobridge/lib/bcpkix-jdk15on-1.54.jar:/usr/share/jitsi-videobridge/lib/bcprov-jdk15on-1.54.jar:/usr/share/jitsi-videobridge/lib/callstats-java-sdk-5.0.0.jar:/usr/share/jitsi-videobridge/lib/cglib-nodep-2.2.2.jar:/usr/share/jitsi-videobridge/lib/commons-codec-1.6.jar:/usr/share/jitsi-videobridge/lib/commons-lang3-3.1.jar:/usr/share/jitsi-videobridge/lib/commons-logging-1.2.jar:/usr/share/jitsi-videobridge/lib/concurrentlinkedhashmap-lru-1.0_jdk5.jar:/usr/share/jitsi-videobridge/lib/core-2.0.1.jar:/usr/share/jitsi-videobridge/lib/dnsjava-2.1.7.jar:/usr/share/jitsi-videobridge/lib/dom4j-1.6.1.jar:/usr/share/jitsi-videobridge/lib/fmj-1.0-20161207.221530-23.jar:/usr/share/jitsi-videobridge/lib/gson-2.3.1.jar:/usr/share/jitsi-videobridge/lib/guava-15.0.jar:/usr/share/jitsi-videobridge/lib/httpclient-4.4.jar:/usr/share/jitsi-videobridge/lib/httpcore-4.4.jar:/usr/share/jitsi-videobridge/lib/ice4j-2.0.0-20181005.221549-11.jar:/usr/share/jitsi-videobridge/lib/jain-sip-ri-ossonly-1.2.98c7f8c-jitsi-oss1.jar:/usr/share/jitsi-videobridge/lib/java-dogstatsd-client-2.5.jar:/usr/share/jitsi-videobridge/lib/java-sdp-nist-bridge-1.1.jar:/usr/share/jitsi-videobridge/lib/javax.servlet-api-3.1.0.jar:/usr/share/jitsi-videobridge/lib/jbosh-0.9.0.jar:/usr/share/jitsi-videobridge/lib/jcip-annotations-1.0.jar:/usr/share/jitsi-videobridge/lib/jcl-core-2.8.jar:/usr/share/jitsi-videobridge/lib/jetty-client-9.2.10.v20150310.jar:/usr/share/jitsi-videobridge/lib/jetty-continuation-9.2.10.v20150310.jar:/usr/share/jitsi-videobridge/lib/jetty-http-9.2.10.v20150310.jar:/usr/share/jitsi-videobridge/lib/jetty-io-9.2.10.v20150310.jar:/usr/share/jitsi-videobridge/lib/jetty-proxy-9.2.10.v20150310.jar:/usr/share/jitsi-videobridge/lib/jetty-rewrite-9.2.10.v20150310.jar:/usr/share/jitsi-videobridge/lib/jetty-security-9.2.10.v20150310.jar:/usr/share/jitsi-videobridge/lib/jetty-server-9.2.10.v20150310.jar:/usr/share/jitsi-videobridge/lib/jetty-servlet-9.2.10.v20150310.jar:/usr/share/jitsi-videobridge/lib/jetty-servlets-9.2.10.v20150310.jar:/usr/share/jitsi-videobridge/lib/jetty-util-9.2.10.v20150310.jar:/usr/share/jitsi-videobridge/lib/jetty-webapp-7.0.1.v20091125.jar:/usr/share/jitsi-videobridge/lib/jetty-xml-7.0.1.v20091125.jar:/usr/share/jitsi-videobridge/lib/jicoco-1.1-20180821.201527-7.jar:/usr/share/jitsi-videobridge/lib/jitsi-android-osgi-1.0-20180322.162617-2.jar:/usr/share/jitsi-videobridge/lib/jitsi-configuration-2.13.f6042d3.jar:/usr/share/jitsi-videobridge/lib/jitsi-dnsservice-2.9-20150723.181644-1.jar:/usr/share/jitsi-videobridge/lib/jitsi-fileaccess-2.13.f6042d3.jar:/usr/share/jitsi-videobridge/lib/jitsi-netaddr-2.13.f6042d3.jar:/usr/share/jitsi-videobridge/lib/jitsi-packetlogging-2.13.f6042d3.jar:/usr/share/jitsi-videobridge/lib/jitsi-protocol-2.13.f6042d3.jar:/usr/share/jitsi-videobridge/lib/jitsi-protocol-jabber-2.13.f6042d3.jar:/usr/share/jitsi-videobridge/lib/jitsi-protocol-media-2.13.f6042d3.jar:/usr/share/jitsi-videobridge/lib/jitsi-resourcemanager-2.13.f6042d3.jar:/usr/share/jitsi-videobridge/lib/jitsi-stats-1.0-20180523.024051-5.jar:/usr/share/jitsi-videobridge/lib/jitsi-ui-service-2.13.f6042d3.jar:/usr/share/jitsi-videobridge/lib/jitsi-util-2.13.f6042d3.jar:/usr/share/jitsi-videobridge/lib/jna-4.1.0.jar:/usr/share/jitsi-videobridge/lib/jnsapi-0.0.3-jitsi-smack4.2-3.jar:/usr/share/jitsi-videobridge/lib/jose4j-0.5.1.jar:/usr/share/jitsi-videobridge/lib/json-simple-1.1.1.jar:/usr/share/jitsi-videobridge/lib/jul-to-slf4j-1.7.7.jar:/usr/share/jitsi-videobridge/lib/jxmpp-core-0.6.0.jar:/usr/share/jitsi-videobridge/lib/jxmpp-jid-0.6.0.jar:/usr/share/jitsi-videobridge/lib/jxmpp-util-cache-0.6.0.jar:/usr/share/jitsi-videobridge/lib/libidn-1.15.jar:/usr/share/jitsi-videobridge/lib/libjitsi-1.0-20181119.181042-364.jar:/usr/share/jitsi-videobridge/lib/log4j-1.2.15.jar:/usr/share/jitsi-videobridge/lib/log4j-api-2.3.jar:/usr/share/jitsi-videobridge/lib/log4j-core-2.3.jar:/usr/share/jitsi-videobridge/lib/object-cloner-0.1.jar:/usr/share/jitsi-videobridge/lib/objenesis-2.2.jar:/usr/share/jitsi-videobridge/lib/okhttp-3.9.1.jar:/usr/share/jitsi-videobridge/lib/okio-1.13.0.jar:/usr/share/jitsi-videobridge/lib/orange-extensions-1.3.0.jar:/usr/share/jitsi-videobridge/lib/org.apache.felix.framework-4.4.0.jar:/usr/share/jitsi-videobridge/lib/org.apache.felix.main-4.4.0.jar:/usr/share/jitsi-videobridge/lib/org.osgi.core-4.3.1.jar:/usr/share/jitsi-videobridge/lib/osgi-over-slf4j-1.7.7.jar:/usr/share/jitsi-videobridge/lib/sdes4j-1.1.3.jar:/usr/share/jitsi-videobridge/lib/sdp-api-1.0.jar:/usr/share/jitsi-videobridge/lib/sigar-1.6.4.jar:/usr/share/jitsi-videobridge/lib/slf4j-api-1.7.7.jar:/usr/share/jitsi-videobridge/lib/slf4j-jdk14-1.7.7.jar:/usr/share/jitsi-videobridge/lib/slf4j-simple-1.6.1.jar:/usr/share/jitsi-videobridge/lib/smack-bosh-4.2.1.jar:/usr/share/jitsi-videobridge/lib/smack-core-4.2.2-b1c107f.jar:/usr/share/jitsi-videobridge/lib/smack-debug-4.2.1.jar:/usr/share/jitsi-videobridge/lib/smack-experimental-4.2.1.jar:/usr/share/jitsi-videobridge/lib/smack-extensions-4.2.2-b1c107f.jar:/usr/share/jitsi-videobridge/lib/smack-im-4.2.2-b1c107f.jar:/usr/share/jitsi-videobridge/lib/smack-java7-4.2.1.jar:/usr/share/jitsi-videobridge/lib/smack-legacy-4.2.1.jar:/usr/share/jitsi-videobridge/lib/smack-resolver-javax-4.2.1.jar:/usr/share/jitsi-videobridge/lib/smack-sasl-javax-4.2.1.jar:/usr/share/jitsi-videobridge/lib/smack-tcp-4.2.2-b1c107f.jar:/usr/share/jitsi-videobridge/lib/tinder-1.3.0.jar:/usr/share/jitsi-videobridge/lib/websocket-api-9.2.10.v20150310.jar:/usr/share/jitsi-videobridge/lib/websocket-client-9.2.10.v20150310.jar:/usr/share/jitsi-videobridge/lib/websocket-common-9.2.10.v20150310.jar:/usr/share/jitsi-videobridge/lib/websocket-server-9.2.10.v20150310.jar:/usr/share/jitsi-videobridge/lib/websocket-servlet-9.2.10.v20150310.jar:/usr/share/jitsi-videobridge/lib/weupnp-0.1.4.jar:/usr/share/jitsi-videobridge/lib/xml-apis-1.0.b2.jar:/usr/share/jitsi-videobridge/lib/xmlpull-1.1.3.4a.jar:/usr/share/jitsi-videobridge/lib/xpp3-1.1.4c.jar:/usr/share/jitsi-videobridge/lib/zrtp4j-light-3.2.0-jitsi-1-20150723.002345-1.jar org.jitsi.videobridge.Main --host= --domain=jitsi.domain.cc --port=5347 --secret=ZRHilBC0

dic 17 11:41:55 trisquel systemd[1]: jitsi-videobridge.service: Main process exited, code=exited, status=143/n/a
dic 17 11:41:55 trisquel systemd[1]: Stopped Jitsi Videobridge.
dic 17 11:41:55 trisquel systemd[1]: jitsi-videobridge.service: Unit entered failed state.
dic 17 11:41:55 trisquel systemd[1]: jitsi-videobridge.service: Failed with result 'exit-code'.
dic 17 11:41:55 trisquel systemd[1]: Starting Jitsi Videobridge...
dic 17 11:41:55 trisquel systemd[1]: Started Jitsi Videobridge.
```
And the issue remains.

**Comment by daimoc** [comment]
I get exactly the same error on a fresh install from unstable repo.
There is a error in systemd file jitsi-videobridge.service.
${JVB_HOST:-localhost} is not valid in ExecStart because systemd has it's own command line parsing (https://unix.stackexchange.com/questions/216780/why-does-bash-parameter-expansion-not-work-inside-systemd-service-files).

It should be fixed to : 
ExecStart=/bin/bash -c "exec /usr/share/jitsi-videobridge/jvb.sh --host=$${JVB_HOST:-localhost} --domain=${JVB_HOSTNAME} --port=${JVB_PORT} --secret=${JVB_SECRET} ${JVB_OPTS} < /dev/null >> ${LOGFILE} 2>&1"

Regards,
Damien

**Comment by damencho** [comment]
Make sense.

I'm curious what is the linux and version you saw the problem? I'm testing on ubuntu 18.x and is working fine.

**Comment by daimoc** [comment]
Ubuntu 16.04

**Comment by damencho** [comment]
Have you tested your change there, is it working? I tested it on 18.x and it seems fine.

**Comment by damencho** [comment]
Thanks for testing @Ark74 

@daimoc There is a [PR](https://github.com/jitsi/jitsi-videobridge/pull/732) already with your proposed changes, thanks.

**Comment by Ark74** [comment]
Yep, I can confirm that it fixes the issue :+1:
